phoenix_tar_file: "./data/phoenix-2014-T.v3.tar.gz"
# If already extracted, set the path, or else leave it empty
phoenix_extracted_folder: "./data/PHOENIX-2014-T-release-v3/PHOENIX-2014-T"
# Folder where the extracted data will be stored
target_folder: "./data/extracted_phoenix"

# Folder where the logs will be stored
log_folder: "./script_logs"
# Video framerate
video_fps: 25

# Use BIN or not
use_bin: True
bin_config:
  num_interpolation: 7
  time_step: 0.5
  model_option_yaml: "./assets/BIN/train_adobe_stage4.yml"
  model_net_name: "bin_stage4"

# Convert VDO to skeletons config
vdo_to_skeletons_config:
# Normal settings
  is_return_landmarked_vdo: False
  landmarks_format: 'pixel'
  save_format: 'npy'
  save_stats: True

  # Refinement settings
  max_distance_between_predicted_hand_and_approximated_hand: 1000

  # Model settings
  face_model:
    face_landmarker_model_path: ./assets/face_landmarker.task
    min_face_detection_confidence: 0.0
    min_face_presence_confidence: 0.0
    min_tracking_confidence: 0.0
    max_num_faces: 1
    output_face_blendshapes: True
    replace_not_found_method: 'previous'
  hand_model:
    max_num_hands: 3
    min_detection_confidence: 0.2
    min_tracking_confidence: 0.2
    replace_not_found_method: 'previous'
  pose_model:
    min_detection_confidence: 0.1
    min_tracking_confidence: 0.0
    replace_not_found_method: 'previous'