# Data parameters
joint_size: 1659
# Window size -1 means that the whole sequence is used
window_size: -1

# Wandb parameters
wandb_api_key: <insert your key here>

# Training parameters
batch_size: 256
max_epochs: 10000
save_every_n_epochs: 10
model_hyperparameters:
  learning_rate_scheduler: 'lambda'
  learning_rate:
    - [0, 6666, 0.0002]
    - [6667, 9999999, 0.00001]
  betas:
    - 0.9
    - 0.99
  L: 3
  codebook_size: 512
  quantizer_decay: 0.99
  skels_dim: 126
  embedding_dim: 1024
  is_focus_hand_mode: False
  ratio_for_hand: 0.9
  activation_type: 'tanh'
data_spec: "hand"

# Paths
# train_data_path: '/home/cpgang/PP/extracted_phoenix_full/train_rel_angle.skels'
train_data_tensor_path: '/home/cpgang/PP/extracted_phoenix_full/train.skels.tensor'
# val_data_path: '/home/cpgang/PP/extracted_phoenix_full/dev_rel_angle.skels'
val_data_tensor_path: '/home/cpgang/PP/extracted_phoenix_full/dev.skels.tensor'
is_data_has_timestamp: False
save_weight_path: '/home/cpgang/PP/trained_model_ckpt/best_vq_vae_posi2_hand.pth'
log_folder_name: 'best_vq_vae_posi2_hand'
wandb_save_dir: '/home/cpgang/PP/wandb_log'
resume_weight_path: ''
pretrained_weight_path: ''

# Is data normalized before training
normalize_data: False