# Folder name
vdo_folder: ./assets/
output_folder: ./mediapipe_skeleton/

# Normal settings
is_return_landmarked_vdo: True
landmarks_format: 'normalized'
save_format: 'npy'

# Model settings
face_model:
  face_landmarker_model_path: ./assets/face_landmarker_v2_with_blendshapes.task
  min_face_detection_confidence: 0.0
  min_face_presence_confidence: 0.0
  min_tracking_confidence: 0.0
  max_num_faces: 1
  output_face_blendshapes: True
  replace_not_found_method: 'previous'
hand_model:
  hand_landmarker_model_path: ./assets/hand_landmarker.task
  max_num_hands: 4
  min_hand_detection_confidence: 0.1
  min_hand_presence_confidence: 0.01
  min_tracking_confidence: 0.01
  replace_not_found_method: 'previous'
pose_model:
  pose_landmarker_model_path: ./assets/pose_landmarker.task
  max_num_poses: 2
  min_pose_detection_confidence: 0.1
  min_pose_presence_confidence: 0.1
  min_tracking_confidence: 0.0
  output_segmentation_masks: False
  replace_not_found_method: 'previous'