# Folder name
vdo_folder: ./assets/
# vdo_file: assets/01March_2011_Tuesday_tagesschau-2211-deblurred-with-BIN.mp4
output_folder: ./mediapipe_skeleton_test/

# Normal settings
is_return_landmarked_vdo: True
landmarks_format: 'pixel'
save_format: 'npy'
save_stats: True

# Refinement settings
max_distance_between_predicted_hand_and_approximated_hand: 1000

# Model settings
face_model:
  min_detection_confidence: 0.0
  min_tracking_confidence: 0.0
  max_num_faces: 1
  replace_not_found_method: 'previous'
hand_model:
  max_num_hands: 3
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5
  replace_not_found_method: 'previous'
pose_model:
  min_detection_confidence: 0.1
  min_tracking_confidence: 0.0
  replace_not_found_method: 'previous'